parameters:
    ongr_oxid.triggers.seo_history.track_fields:
      - OXOBJECTID
      - OXIDENT
      - OXSHOPID
      - OXLANG
      - OXHITS
      - OXINSERT
      - OXTIMESTAMP

services:
    # INSERT and UPDATE
    ongr_oxid.triggers.oxseo_history_update.articles:
        class: %ongr_oxid.triggers.related_table.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=NEW.OXOBJECTID, product, U, 1]

    ongr_oxid.triggers.oxseo_history_update.category:
        class: %ongr_oxid.triggers.related_table.class%
        arguments: [oxcategories, oxcategories.OXID, oxcategories.OXID=NEW.OXOBJECTID, category, U, 1]

    ongr_oxid.triggers.oxseo_history_update.content:
        class: %ongr_oxid.triggers.related_table.class%
        arguments: [oxcontents, oxcontents.OXID, oxcontents.OXID=NEW.OXOBJECTID, content, U, 1]

    # DELETE
    ongr_oxid.triggers.oxseo_history_delete.articles:
        class: %ongr_oxid.triggers.related_table.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=OLD.OXOBJECTID, product, U, 1]

    ongr_oxid.triggers.oxseo_history_delete.category:
        class: %ongr_oxid.triggers.related_table.class%
        arguments: [oxcategories, oxcategories.OXID, oxcategories.OXID=OLD.OXOBJECTID, category, U, 1]

    ongr_oxid.triggers.oxseo_history_delete.content:
        class: %ongr_oxid.triggers.related_table.class%
        arguments: [oxcontents, oxcontents.OXID, oxcontents.OXID=Old.OXOBJECTID, content, U, 1]

    # Seo history (`oxseohistory`) triggers
    ongr_oxid.triggers.oxseo_history_insert:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxseohistory, C]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_history_insert }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_update.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_update.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_update.content]]

    ongr_oxid.triggers.oxseo_history_update:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxseohistory, U, %ongr_oxid.triggers.seo_history.track_fields%]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_history_oxobjects_update }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_update.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_update.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_update.content]]

    ongr_oxid.triggers.oxseo_history_delete:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxseohistory, D]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_history_delete }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_delete.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_delete.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_history_delete.content]]
